[package]
name = "weather"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.10.1"
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
grib = "0.13.0"
reqwest = "0.12.23"
tokio = { version = "1.40", features = ["full"] }
